[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3002"
